### ISSUE TITLE
REQ: NanaZip Support!

### ISSUE THREAD

**Issue by c-michail** [Wilenty/7-Zip-Theme-Manager-remake-of-version-2.1#4]
Hello,
  Can you please support for Nanazip ?
  https://github.com/M2Team/NanaZip
  
Thank you

**Comment by Wilenty** [comment]
Hello,
why I should support the NanaZip?

You mean the work (my help with it), the money, or promote NanaZip?

You can also consider support my work.

Thanks in advance!

**Comment by c-michail** [comment]
I mean to change the icons of Nanazip which it's a modified 7z for Windows 11.

Thank you

**Comment by Wilenty** [comment]
If they uses the same icons names, there should be not a problem - it should work almost "out-of-the-box"...

I will look at it if they uses this same names or not. And I will let you know here.

But, please take in mind that I won't work on this old AutoIT script, please look at the successor.

**Comment by Wilenty** [comment]
Hello [chmichael](https://github.com/chmichael),
I've checked and it looks that NanaZip uses the same icon names as the original program.

So, now I need a while of the time to think "how to solve" for both of them. Because the file names are different...

**Comment by Wilenty** [comment]
Hello,
I added preliminary support for NanaZip, and shared as a pre-release. So, if you have a while of the time - you can check it.

https://github.com/Wilenty/7zTC-7-ZIP-Theme-Changer/releases/tag/v1.5b

If you have an account on MDL or G3D, you can share your nickname or link to your profile - will try to contact you privately. I want to ask you something non-publicly, but if you don't want it - no problem at all.

**Comment by c-michail** [comment]
Hello,
  Here's my telegram: @chmichael7
  It detected Nanazip correctly but for some reason it can't patch it.

Attached the logs
[7zTC [Apply].txt](https://github.com/Wilenty/7-Zip-Theme-Manager-remake-of-version-2.1/files/8192626/7zTC.Apply.txt)
!

**Comment by Wilenty** [comment]
Hello,
thanks for the LOG.

Before empty lines we see: "Access is denied (5)"

So, for first uninstall NanaZip, then get the latest ver. from there: https://github.com/M2Team/NanaZip/releases

Select the *.msixbundle in the installer for install, it will extract it in the "C:\Program Files\NanaZip" (for example)

And after that you'll be able to change its theme(s).

Please check and let me know...

**Comment by c-michail** [comment]
Hello,
  Since is a WindowsApp it will always install "C:\Program Files\WindowsApps\40174MouriNaruto.NanaZip_1.0.95.0_x64__gnj4mf6z9tkrc" which 7z Theme manager seems can't get the permission to modify it! 
   I'll try to make an Inno Setup script which it will install it into "Program Files". I let you know!

**Comment by Wilenty** [comment]
Hello,
for first, new app name is "7z Theme Changer", but not the "7z Theme Manager" ;)

For second, my program uses Windows API, so it's not the problem of my program that Windows installs the APP's from store by TrustedInstaller account (Windows Update) and we have no access to it.

So, it's not the problem by my program, because I used Windows API functions to modify files, but Windows API can't edit those files, because it's not possible...

You don't have to create any InnoSetup installers to install it, it's already done in my InnoSetup. :D
As I wrote before, get the latest installer of NanaZip (*.msixbundle) from there: https://github.com/M2Team/NanaZip/releases/latest
In my program select the NanaZip, then select the *.msixbundle for installation in "Install NanaZip?" - it will extract the correct files into selected location for installation, and will be able to modify resources.

So, please check my solution, which I prepared before. :)

BTW, Removed detection of installed NanaZip from store: https://github.com/Wilenty/7zTC-7-ZIP-Theme-Changer/releases/tag/v1.6b

**Comment by c-michail** [comment]
Hello,
  Ok! Done your procedure but it doesn't register the shell extension either on icons!
  Although the application in C:\Program Files\Nanazip is correctly modified!

Can you do something about that ?

Thanks

**Comment by Wilenty** [comment]
Yes, its not register the shell-extensions, nor icons, but you can do it in the program settings: (tab) "Integration" -> "Open Windows settings to associate with NanaZip"

"Can you do something about that ?"
I will think about it. :)

**Comment by c-michail** [comment]
<Yes, its not register the shell-extensions, nor icons, but you can do it in the program settings: (tab) "Integration" -> "Open Windows settings to associate with NanaZip">

Well it's a bit of a pain to do that manually! 😄 

Write down your $ATOM crypto address to send you one!

Thank you for everything!

**Comment by Wilenty** [comment]
You can support me on Patreon: https://patreon.com/Wilenty
or Ko-Fi: https://ko-fi.com/Wilenty
if you want, but I would prefer the Patreon, because the amount of money is too low to transfer it :]

Thank you for good suggestion about my program modification, I will try to contact you as I wrote, but a bit later...

Thank you too!

**Comment by c-michail** [comment]
I send the donation now if you can find a way for the shell extensions to work it would be awesome! :)
The nanazip source code is there so you can take a look.

Thank you

**Comment by Wilenty** [comment]
Hello,
THANKS!
But, please wait a while, I'm compiling the version for you (right now), and I will write to you on Ko-Fi service.

Thank you.

**Comment by c-michail** [comment]
I'm not signed in the Ko-FI so use telegram if you want!

**Comment by Wilenty** [comment]
No problem, you will get the message from me from Ko-Fi on your e-mail, so ;)

**Comment by Wilenty** [comment]
I'll send you the message from Ko-Fi (already), so, if you have any problem - let me know.
